/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-01 02:54:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class inscription_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/ILISI2DOCS/Projets/ProjetEcommerce/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/location-app/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664449878000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1771968634122L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Créer un compte — TechShop</title>\n");
      out.write("  <!-- TailwindCSS CDN -->\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("  <!-- Configuration Tailwind personnalisée -->\n");
      out.write("  <script>\n");
      out.write("    tailwind.config = {\n");
      out.write("      theme: {\n");
      out.write("        extend: {\n");
      out.write("          colors: {\n");
      out.write("            gold: '#D4AF37',\n");
      out.write("            'gold-dark': '#B8860B',\n");
      out.write("            'blue-ice': '#7eb8f7',\n");
      out.write("            'green-ok': '#4cdb8f',\n");
      out.write("            'dark-bg': '#0a0a0f',\n");
      out.write("            'bg-elevated': '#111118',\n");
      out.write("            'bg-card': '#1a1a24',\n");
      out.write("            'border': '#2a2a35',\n");
      out.write("            'border-strong': '#3a3a45',\n");
      out.write("            'text-muted': '#9ca3af',\n");
      out.write("            'text-secondary': '#d1d5db',\n");
      out.write("          },\n");
      out.write("          fontFamily: {\n");
      out.write("            display: ['Syne', 'sans-serif'],\n");
      out.write("            sans: ['DM Sans', 'sans-serif'],\n");
      out.write("          },\n");
      out.write("          animation: {\n");
      out.write("            'fade-up': 'fadeUp 0.6s ease-out forwards',\n");
      out.write("          },\n");
      out.write("          keyframes: {\n");
      out.write("            fadeUp: {\n");
      out.write("              '0%': { opacity: '0', transform: 'translateY(20px)' },\n");
      out.write("              '100%': { opacity: '1', transform: 'translateY(0)' },\n");
      out.write("            }\n");
      out.write("          }\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-dark-bg text-gray-100 font-sans antialiased min-h-screen\">\n");
      out.write("\n");
      out.write("<div class=\"min-h-screen grid grid-cols-1 md:grid-cols-2\">\n");
      out.write("\n");
      out.write("  <!-- Panneau gauche -->\n");
      out.write("  <div class=\"bg-gradient-to-br from-[#0a0a0f] to-[#0d0d18] hidden md:flex flex-col justify-center p-16 relative overflow-hidden\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"absolute inset-0\" \n");
      out.write("         style=\"background: radial-gradient(ellipse 60% 50% at 60% 30%, rgba(126,184,247,0.1) 0%, transparent 70%),\n");
      out.write("                         radial-gradient(ellipse 40% 40% at 20% 80%, rgba(240,192,64,0.08) 0%, transparent 60%);\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"relative z-10\">\n");
      out.write("      <div class=\"font-display text-2xl font-extrabold mb-10\">\n");
      out.write("        <span class=\"text-gold\">⚡</span> TechShop\n");
      out.write("      </div>\n");
      out.write("      <h1 class=\"font-display text-5xl font-extrabold leading-tight tracking-tighter mb-5\">\n");
      out.write("        Rejoignez<br><span class=\"text-blue-ice\">la communauté</span><br>TechShop.\n");
      out.write("      </h1>\n");
      out.write("      <p class=\"text-gray-400 leading-relaxed max-w-sm\">\n");
      out.write("        Créez votre compte en quelques secondes et accédez à des milliers de produits électroniques au meilleur prix.\n");
      out.write("      </p>\n");
      out.write("      <div class=\"mt-12 grid grid-cols-2 gap-4\">\n");
      out.write("        <div class=\"bg-gray-800/50 border border-gray-700 rounded-lg p-5\">\n");
      out.write("          <div class=\"font-display text-3xl font-extrabold text-gold\">14+</div>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\">Produits premium</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"bg-gray-800/50 border border-gray-700 rounded-lg p-5\">\n");
      out.write("          <div class=\"font-display text-3xl font-extrabold text-blue-ice\">5</div>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\">Catégories</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Formulaire d'inscription -->\n");
      out.write("  <main class=\"flex items-center justify-center p-8 md:p-12 bg-gray-900 overflow-y-auto\">\n");
      out.write("    <div class=\"w-full max-w-lg animate-fade-up\">\n");
      out.write("\n");
      out.write("      <div class=\"mb-2\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/catalogue\"\n");
      out.write("           class=\"text-sm text-gray-500 hover:text-gold inline-flex items-center gap-1 transition-colors\">\n");
      out.write("          ← Retour au catalogue\n");
      out.write("        </a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <h2 class=\"font-display text-3xl font-bold tracking-tight mb-1\">\n");
      out.write("        Créer un compte\n");
      out.write("      </h2>\n");
      out.write("      <p class=\"text-gray-400 text-sm mb-8\">\n");
      out.write("        Tous les champs marqués <span class=\"text-gold\">*</span> sont obligatoires\n");
      out.write("      </p>\n");
      out.write("\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/inscription\"\n");
      out.write("            method=\"post\"\n");
      out.write("            novalidate\n");
      out.write("            id=\"inscriptionForm\"\n");
      out.write("            aria-label=\"Formulaire d'inscription\"\n");
      out.write("            class=\"space-y-5\">\n");
      out.write("\n");
      out.write("        <!-- Prénom et Nom -->\n");
      out.write("        <div class=\"grid grid-cols-2 gap-4\">\n");
      out.write("          <div>\n");
      out.write("            <label class=\"block text-sm font-medium text-gray-300 mb-2\" for=\"prenom\">\n");
      out.write("              Prénom <span class=\"text-gold\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input type=\"text\" id=\"prenom\" name=\"prenom\"\n");
      out.write("                   class=\"w-full h-12 px-4 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"Jean\"\n");
      out.write("                   value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("                   required minlength=\"2\"\n");
      out.write("                   autocomplete=\"given-name\"\n");
      out.write("                   aria-required=\"true\">\n");
      out.write("          </div>\n");
      out.write("          <div>\n");
      out.write("            <label class=\"block text-sm font-medium text-gray-300 mb-2\" for=\"nom\">\n");
      out.write("              Nom <span class=\"text-gold\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <input type=\"text\" id=\"nom\" name=\"nom\"\n");
      out.write("                   class=\"w-full h-12 px-4 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"Dupont\"\n");
      out.write("                   value=\"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("                   required minlength=\"2\"\n");
      out.write("                   autocomplete=\"family-name\"\n");
      out.write("                   aria-required=\"true\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Email -->\n");
      out.write("        <div>\n");
      out.write("          <label class=\"block text-sm font-medium text-gray-300 mb-2\" for=\"email\">\n");
      out.write("            Adresse e-mail <span class=\"text-gold\">*</span>\n");
      out.write("          </label>\n");
      out.write("          <div class=\"relative\">\n");
      out.write("            <span class=\"absolute left-4 top-1/2 -translate-y-1/2 text-gray-500\" aria-hidden=\"true\">  </span>\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\"\n");
      out.write("                   class=\"w-full h-12 pl-11 pr-4 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"jean.dupont@email.com\"\n");
      out.write("                   value=\"");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("                   required\n");
      out.write("                   autocomplete=\"email\"\n");
      out.write("                   aria-required=\"true\"\n");
      out.write("                   aria-describedby=\"email-hint\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\" id=\"email-hint\">Cet email servira d'identifiant de connexion</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Mot de passe -->\n");
      out.write("        <div>\n");
      out.write("          <label class=\"block text-sm font-medium text-gray-300 mb-2\" for=\"password\">\n");
      out.write("            Mot de passe <span class=\"text-gold\">*</span>\n");
      out.write("          </label>\n");
      out.write("          <div class=\"relative\">\n");
      out.write("            <span class=\"absolute left-4 top-1/2 -translate-y-1/2 text-gray-500\" aria-hidden=\"true\"> </span>\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\"\n");
      out.write("                   class=\"w-full h-12 pl-11 pr-12 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"Minimum 6 caractères\"\n");
      out.write("                   required minlength=\"6\"\n");
      out.write("                   autocomplete=\"new-password\"\n");
      out.write("                   aria-required=\"true\"\n");
      out.write("                   aria-describedby=\"pwd-hint\"\n");
      out.write("                   oninput=\"checkPasswordStrength(this.value)\">\n");
      out.write("            <span class=\"absolute right-4 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gold cursor-pointer\" \n");
      out.write("                  onclick=\"togglePassword('password', this)\"\n");
      out.write("                  role=\"button\" \n");
      out.write("                  tabindex=\"0\" \n");
      out.write("                  aria-label=\"Afficher le mot de passe\">👁️</span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\" id=\"pwd-hint\">Minimum 6 caractères</div>\n");
      out.write("          <div id=\"pwd-strength\" class=\"mt-2 hidden\">\n");
      out.write("            <div class=\"flex gap-1\">\n");
      out.write("              <div class=\"h-1 flex-1 rounded-full bg-gray-700 transition-all duration-300\" id=\"sb1\"></div>\n");
      out.write("              <div class=\"h-1 flex-1 rounded-full bg-gray-700 transition-all duration-300\" id=\"sb2\"></div>\n");
      out.write("              <div class=\"h-1 flex-1 rounded-full bg-gray-700 transition-all duration-300\" id=\"sb3\"></div>\n");
      out.write("              <div class=\"h-1 flex-1 rounded-full bg-gray-700 transition-all duration-300\" id=\"sb4\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"pwd-strength-label\" class=\"text-xs text-gray-500 mt-1\"></div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Adresse -->\n");
      out.write("        <div>\n");
      out.write("          <label class=\"block text-sm font-medium text-gray-300 mb-2\" for=\"adresse\">Adresse de livraison</label>\n");
      out.write("          <textarea id=\"adresse\" name=\"adresse\"\n");
      out.write("                    class=\"w-full px-4 py-3 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                    placeholder=\"12 Rue de la Paix, 75002 Paris\"\n");
      out.write("                    rows=\"2\"\n");
      out.write("                    autocomplete=\"street-address\">");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("</textarea>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\">Peut être modifiée lors de chaque commande</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- CGU -->\n");
      out.write("        <div class=\"flex items-start gap-3\">\n");
      out.write("          <input type=\"checkbox\" id=\"cgu\" name=\"cgu\"\n");
      out.write("                 class=\"w-4 h-4 mt-1 accent-gold bg-gray-700 border-gray-600 rounded focus:ring-gold focus:ring-2\"\n");
      out.write("                 required>\n");
      out.write("          <label for=\"cgu\" class=\"text-sm text-gray-400 leading-relaxed cursor-pointer\">\n");
      out.write("            J'accepte les <a href=\"#\" class=\"text-gold hover:text-gold-dark transition-colors\">Conditions Générales d'Utilisation</a>\n");
      out.write("            et la <a href=\"#\" class=\"text-gold hover:text-gold-dark transition-colors\">Politique de confidentialité</a>\n");
      out.write("          </label>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Submit -->\n");
      out.write("        <button type=\"submit\" \n");
      out.write("                class=\"w-full h-12 bg-gradient-to-r from-gold to-gold-dark text-gray-900 font-medium rounded-xl hover:shadow-lg hover:shadow-gold/20 transition-all duration-300 flex items-center justify-center gap-2\">\n");
      out.write("          <span>Créer mon compte</span>\n");
      out.write("          <span aria-hidden=\"true\">  </span>\n");
      out.write("        </button>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("      <!-- Lien connexion -->\n");
      out.write("      <div class=\"text-center mt-6 text-sm text-gray-400\">\n");
      out.write("        Déjà un compte ?\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" class=\"text-gold font-semibold hover:text-gold-dark transition-colors\">Se connecter</a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  function togglePassword(id, btn) {\n");
      out.write("    const input = document.getElementById(id);\n");
      out.write("    input.type = input.type === 'password' ? 'text' : 'password';\n");
      out.write("    btn.textContent = input.type === 'password' ? '👁️' : '🙈';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  function checkPasswordStrength(pwd) {\n");
      out.write("    const bars = ['sb1','sb2','sb3','sb4'];\n");
      out.write("    const label = document.getElementById('pwd-strength-label');\n");
      out.write("    const container = document.getElementById('pwd-strength');\n");
      out.write("    container.style.display = pwd.length > 0 ? 'block' : 'none';\n");
      out.write("\n");
      out.write("    let score = 0;\n");
      out.write("    if (pwd.length >= 6) score++;\n");
      out.write("    if (pwd.length >= 10) score++;\n");
      out.write("    if (/[A-Z]/.test(pwd) && /[0-9]/.test(pwd)) score++;\n");
      out.write("    if (/[^A-Za-z0-9]/.test(pwd)) score++;\n");
      out.write("\n");
      out.write("    const colors = ['', '#f06060', '#f0c040', '#7eb8f7', '#4cdb8f'];\n");
      out.write("    const labels = ['', 'Trop court', 'Faible', 'Moyen', 'Fort'];\n");
      out.write("    bars.forEach((id, i) => {\n");
      out.write("      document.getElementById(id).style.background = i < score ? colors[score] : '#374151';\n");
      out.write("    });\n");
      out.write("    label.textContent = labels[score] || '';\n");
      out.write("    label.style.color = colors[score];\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  document.getElementById('inscriptionForm').addEventListener('submit', function(e) {\n");
      out.write("    const cgu = document.getElementById('cgu');\n");
      out.write("    if (!cgu.checked) {\n");
      out.write("      e.preventDefault();\n");
      out.write("      alert('Veuillez accepter les Conditions Générales d\\'Utilisation');\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/common/inscription.jsp(99,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty erreur}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        <div class=\"mb-6 p-4 bg-rose-900/50 border border-rose-600 rounded-xl flex items-center gap-3 text-rose-200\" role=\"alert\">\n");
        out.write("          <span class=\"text-2xl\" aria-hidden=\"true\">⚠️</span>\n");
        out.write("          <span>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${erreur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\n");
        out.write("        </div>\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/common/inscription.jsp(122,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prenom}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/common/inscription.jsp(134,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nom}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/common/inscription.jsp(151,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /WEB-INF/common/inscription.jsp(200,50) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${adresse}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }
}
