/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-01 02:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/ILISI2DOCS/Projets/ProjetEcommerce/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/location-app/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664449878000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1771968634122L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Connexion — TechShop</title>\n");
      out.write("  <!-- TailwindCSS CDN -->\n");
      out.write("  <script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("  <!-- Configuration Tailwind personnalisée -->\n");
      out.write("  <script>\n");
      out.write("    tailwind.config = {\n");
      out.write("      theme: {\n");
      out.write("        extend: {\n");
      out.write("          colors: {\n");
      out.write("            gold: '#D4AF37',\n");
      out.write("            'gold-dark': '#B8860B',\n");
      out.write("            'gold-glow': 'rgba(212, 175, 55, 0.15)',\n");
      out.write("            'dark-bg': '#0a0a0f',\n");
      out.write("            'bg-elevated': '#111118',\n");
      out.write("            'border': '#2a2a35',\n");
      out.write("            'border-strong': '#3a3a45',\n");
      out.write("          },\n");
      out.write("          fontFamily: {\n");
      out.write("            display: ['Syne', 'sans-serif'],\n");
      out.write("            sans: ['DM Sans', 'sans-serif'],\n");
      out.write("          },\n");
      out.write("          animation: {\n");
      out.write("            'fade-up': 'fadeUp 0.6s ease-out forwards',\n");
      out.write("          },\n");
      out.write("          keyframes: {\n");
      out.write("            fadeUp: {\n");
      out.write("              '0%': { opacity: '0', transform: 'translateY(20px)' },\n");
      out.write("              '100%': { opacity: '1', transform: 'translateY(0)' },\n");
      out.write("            }\n");
      out.write("          }\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Sans:wght@300;400;500&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body class=\"bg-dark-bg text-gray-100 font-sans antialiased min-h-screen\">\n");
      out.write("\n");
      out.write("<div class=\"min-h-screen grid grid-cols-1 md:grid-cols-2\">\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("  <div class=\"bg-gradient-to-br from-[#0a0a0f] via-[#111118] to-[#0d0d18] hidden md:flex flex-col justify-center items-start p-16 relative overflow-hidden\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"absolute inset-0\" \n");
      out.write("         style=\"background: radial-gradient(ellipse 60% 60% at 30% 40%, rgba(240,192,64,0.12) 0%, transparent 70%),\n");
      out.write("                         radial-gradient(ellipse 40% 40% at 70% 70%, rgba(126,184,247,0.08) 0%, transparent 60%);\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"relative z-10\">\n");
      out.write("      <div class=\"flex items-center gap-3 mb-12\">\n");
      out.write("        <div class=\"w-[42px] h-[42px] bg-gradient-to-br from-gold to-amber-600 rounded-lg flex items-center justify-center text-xl shadow-[0_0_30px_rgba(212,175,55,0.3)]\">\n");
      out.write("          ⚡\n");
      out.write("        </div>\n");
      out.write("        <span class=\"font-display text-2xl font-extrabold\">Tech<span class=\"text-gold\">Shop</span></span>\n");
      out.write("      </div>\n");
      out.write("      <h1 class=\"font-display text-5xl font-extrabold leading-tight tracking-tighter mb-6\">\n");
      out.write("        L'excellence<br><span class=\"text-gold\">technologique</span><br>à portée de main.\n");
      out.write("      </h1>\n");
      out.write("      <p class=\"text-gray-400 text-base leading-relaxed max-w-md mb-12\">\n");
      out.write("        Découvrez notre catalogue de produits électroniques premium — smartphones, laptops, audio et bien plus.\n");
      out.write("      </p>\n");
      out.write("      <div class=\"space-y-4\">\n");
      out.write("        <div class=\"flex items-center gap-4\">\n");
      out.write("          <div class=\"w-9 h-9 bg-gold-glow border border-gold/20 rounded-lg flex items-center justify-center text-base shrink-0\">  </div>\n");
      out.write("          <span class=\"text-sm text-gray-400\">Paiement sécurisé & données protégées</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"flex items-center gap-4\">\n");
      out.write("          <div class=\"w-9 h-9 bg-gold-glow border border-gold/20 rounded-lg flex items-center justify-center text-base shrink-0\">  </div>\n");
      out.write("          <span class=\"text-sm text-gray-400\">Livraison express en 24h</span>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"flex items-center gap-4\">\n");
      out.write("          <div class=\"w-9 h-9 bg-gold-glow border border-gold/20 rounded-lg flex items-center justify-center text-base shrink-0\">  </div>\n");
      out.write("          <span class=\"text-sm text-gray-400\">Garantie constructeur sur tous les produits</span>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  ");
      out.write("\n");
      out.write("  <main class=\"flex items-center justify-center p-8 md:p-12 bg-gray-900\">\n");
      out.write("    <div class=\"w-full max-w-md animate-fade-up\">\n");
      out.write("\n");
      out.write("      <h2 class=\"font-display text-3xl font-bold tracking-tight mb-1\">Bon retour   </h2>\n");
      out.write("      <p class=\"text-gray-400 text-sm mb-8\">Connectez-vous à votre compte TechShop</p>\n");
      out.write("\n");
      out.write("      ");
      out.write("\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("      ");
      out.write("\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"\n");
      out.write("            method=\"post\"\n");
      out.write("            novalidate\n");
      out.write("            id=\"loginForm\"\n");
      out.write("            aria-label=\"Formulaire de connexion\"\n");
      out.write("            class=\"space-y-5\">\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("          <div class=\"flex justify-between items-baseline mb-2\">\n");
      out.write("            <label class=\"text-sm font-medium text-gray-300\" for=\"email\">\n");
      out.write("              Adresse e-mail <span class=\"text-gold\" aria-hidden=\"true\">*</span>\n");
      out.write("            </label>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"relative\">\n");
      out.write("            <span class=\"absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 text-sm\" aria-hidden=\"true\">      </span>\n");
      out.write("            <input type=\"email\"\n");
      out.write("                   id=\"email\"\n");
      out.write("                   name=\"email\"\n");
      out.write("                   class=\"w-full h-12 pl-10 pr-4 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"votre@email.com\"\n");
      out.write("                   value=\"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("                   required\n");
      out.write("                   autocomplete=\"email\"\n");
      out.write("                   aria-describedby=\"email-hint\"\n");
      out.write("                   aria-required=\"true\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"text-xs text-gray-500 mt-1\" id=\"email-hint\">Entrez l'email associé à votre compte</div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div>\n");
      out.write("          <div class=\"flex justify-between items-baseline mb-2\">\n");
      out.write("            <label class=\"text-sm font-medium text-gray-300\" for=\"password\">\n");
      out.write("              Mot de passe <span class=\"text-gold\" aria-hidden=\"true\">*</span>\n");
      out.write("            </label>\n");
      out.write("            <a href=\"#\" class=\"text-xs text-gold hover:text-gold-dark transition-colors\">Mot de passe oublié ?</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"relative\">\n");
      out.write("            <span class=\"absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 text-sm\" aria-hidden=\"true\">       </span>\n");
      out.write("            <input type=\"password\"\n");
      out.write("                   id=\"password\"\n");
      out.write("                   name=\"password\"\n");
      out.write("                   class=\"w-full h-12 pl-10 pr-12 bg-gray-800/50 border border-gray-700 rounded-xl text-gray-100 placeholder-gray-600 focus:outline-none focus:border-gold focus:ring-2 focus:ring-gold/20 transition-all duration-300\"\n");
      out.write("                   placeholder=\"••••••••\"\n");
      out.write("                   required\n");
      out.write("                   autocomplete=\"current-password\"\n");
      out.write("                   aria-required=\"true\">\n");
      out.write("            <span class=\"absolute right-3 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gold cursor-pointer text-sm select-none\" \n");
      out.write("                  onclick=\"togglePassword('password', this)\"\n");
      out.write("                  role=\"button\" \n");
      out.write("                  tabindex=\"0\" \n");
      out.write("                  aria-label=\"Afficher/masquer le mot de passe\">👁️</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"flex items-center gap-2\">\n");
      out.write("          <input type=\"checkbox\" id=\"remember\" name=\"remember\"\n");
      out.write("                 class=\"w-4 h-4 accent-gold bg-gray-700 border-gray-600 rounded focus:ring-gold focus:ring-2\">\n");
      out.write("          <label for=\"remember\" class=\"text-sm text-gray-400 cursor-pointer select-none\">\n");
      out.write("            Se souvenir de moi\n");
      out.write("          </label>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <button type=\"submit\"\n");
      out.write("                class=\"w-full h-12 bg-gradient-to-r from-gold to-gold-dark text-gray-900 font-medium rounded-xl hover:shadow-lg hover:shadow-gold/20 transition-all duration-300 flex items-center justify-center gap-2\"\n");
      out.write("                id=\"submitBtn\">\n");
      out.write("          <span>Se connecter</span>\n");
      out.write("          <span aria-hidden=\"true\">→</span>\n");
      out.write("        </button>\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("      <div class=\"flex items-center gap-4 my-6\">\n");
      out.write("        <div class=\"flex-1 h-px bg-gray-800\"></div>\n");
      out.write("        <span class=\"text-xs text-gray-500\">ou</span>\n");
      out.write("        <div class=\"flex-1 h-px bg-gray-800\"></div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"text-center text-sm text-gray-400\">\n");
      out.write("        Pas encore de compte ?\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/inscription\" class=\"text-gold font-semibold hover:text-gold-dark transition-colors\">Créer un compte gratuitement</a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      ");
      out.write("\n");
      out.write("      <div class=\"mt-8 p-4 bg-gray-800/50 border border-gray-700 rounded-xl text-xs\">\n");
      out.write("        <div class=\"text-gray-400 font-semibold mb-2\">🧪 Comptes de test</div>\n");
      out.write("        <div class=\"text-gray-500\">Admin : admin@ecommerce.com / Admin2024!</div>\n");
      out.write("        <div class=\"text-gray-500\">Client : jean.dupont@test.com / Test1234!</div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("  // Contrainte qualité : validation côté client en complément du serveur\n");
      out.write("  function togglePassword(id, btn) {\n");
      out.write("    const input = document.getElementById(id);\n");
      out.write("    input.type = input.type === 'password' ? 'text' : 'password';\n");
      out.write("    btn.textContent = input.type === 'password' ? '👁️' : '🙈';\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  // Validation HTML5 améliorée avec accessibilité\n");
      out.write("  document.getElementById('loginForm').addEventListener('submit', function(e) {\n");
      out.write("    const email = document.getElementById('email');\n");
      out.write("    const password = document.getElementById('password');\n");
      out.write("    let valid = true;\n");
      out.write("\n");
      out.write("    if (!email.value.trim() || !/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email.value)) {\n");
      out.write("      email.setCustomValidity('Adresse email invalide');\n");
      out.write("      valid = false;\n");
      out.write("    } else {\n");
      out.write("      email.setCustomValidity('');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    if (!password.value) {\n");
      out.write("      password.setCustomValidity('Le mot de passe est obligatoire');\n");
      out.write("      valid = false;\n");
      out.write("    } else {\n");
      out.write("      password.setCustomValidity('');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    if (!valid) { e.preventDefault(); this.reportValidity(); }\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/common/login.jsp(93,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty succes}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        <div class=\"mb-6 p-4 bg-emerald-900/50 border border-emerald-600 rounded-xl flex items-center gap-3 text-emerald-200\" role=\"alert\">\n");
        out.write("          <span class=\"text-2xl\" aria-hidden=\"true\">   </span>\n");
        out.write("          <span>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${succes}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\n");
        out.write("        </div>\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/common/login.jsp(99,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty erreur}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("        <div class=\"mb-6 p-4 bg-rose-900/50 border border-rose-600 rounded-xl flex items-center gap-3 text-rose-200\" role=\"alert\">\n");
        out.write("          <span class=\"text-2xl\" aria-hidden=\"true\">    </span>\n");
        out.write("          <span>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${erreur}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\n");
        out.write("        </div>\n");
        out.write("      ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/common/login.jsp(130,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
